### PR TITLE
feat: add Toggle to Enable or Disable Connection action

### PR DESCRIPTION
**Pull request by roomac**
Connection action updated to Toggle, Yes & No which mirrors the Enable or Disable Trigger action.

### CODE REVIEW

**Comment by roomac** [comment]
Thanks @Julusian for merging this. However with your updated code `curState` is evaluating as `true` when it needs to be `false` (line 1218). Also `curState` needs to be `true` in all cases when the status value isn’t `-1` otherwise the instance can’t be toggled off when it’s on.

I’ve tested the following to replace lines 1217–19 and it works OK:

```
if (self.instance_status.hasOwnProperty(opt.instance_id)) {
    if (self.instance_status[opt.instance_id][0] == -1) curState = false
    else curState = true
}
```

**Comment by roomac** [comment]
Now updated in my fork at https://github.com/roomac/companion-module-bitfocus-companion/commit/f35b04bf5f4d439f2464eaec44b251469356c09e.

**Comment by Julusian** [comment]
oh good.. thats what I get for not testing it..
Would `curState = self.instance_status[opt.instance_id][0] != -1` also work? It looks like I simply got it inverted. I would prefer to avoid too many if statements when boolean logic would work

**Comment by roomac** [comment]
That works fine, thank you.

**Comment by Julusian** [comment]
Hopefully I didnt mess it up this time. It is in the betas now too

**Comment by roomac** [comment]
Well my code was pretty messy to start with so thanks for sorting it out 😄.

**Pull request merged**
